Repository CytopiaTeam/Cytopia, pull requests merged in 2019-06, with the labels that each got.

#159 Fix json errors
  src/engine/tileManager.cxx
  src/engine/uiManager.cxx
Labels: bug, core

#170 Fixed issue #51
  src/engine/basics/timer.cxx
  src/engine/basics/timer.hxx
  src/engine/eventManager.cxx
  src/engine/eventManager.hxx
  src/game.cxx
Labels: core, enhancement

#185 Terrain Generation Update
  src/engine/map/TerrainGenerator.cxx
  src/engine/map/TerrainGenerator.hxx
Labels: enhancement

#233 [WIP] change Font
  data/resources/fonts/Poco.ttf
  data/resources/settings.json
  src/Game.cxx
  src/engine/Sprite.cxx
  src/engine/UIManager.cxx
  src/engine/UIManager.hxx
  src/engine/basics/Settings.hxx
  src/engine/common/JsonSerialization.hxx
  src/engine/ui/basics/UIElement.cxx
  src/engine/ui/basics/UIElement.hxx
  src/engine/ui/widgets/Button.cxx
  src/engine/ui/widgets/Button.hxx
  src/engine/ui/widgets/Combobox.cxx
  src/engine/ui/widgets/Image.cxx
  src/engine/ui/widgets/Text.cxx
  src/engine/ui/widgets/Text.hxx
  src/engine/ui/widgets/TextField.cxx
  tests/CMakeLists.txt
  tests/ui/widgets/Text.cxx
Labels: enhancement, refactoring, user interface

#246 More Sonarcloud fixes
  src/engine/EventManager.cxx
  src/engine/Map.cxx
  src/engine/UIManager.cxx
  src/engine/WindowManager.cxx
  src/engine/basics/Camera.cxx
  src/engine/ui/basics/Layout.hxx
  src/engine/ui/widgets/TextField.cxx
Labels: core, refactoring

#248 Image opacity modifications and widget documentation
  src/engine/ui/widgets/Button.hxx
  src/engine/ui/widgets/Checkbox.hxx
  src/engine/ui/widgets/Combobox.hxx
  src/engine/ui/widgets/Frame.hxx
  src/engine/ui/widgets/Image.hxx
  src/engine/ui/widgets/Slider.hxx
  src/engine/ui/widgets/Text.hxx
  src/engine/ui/widgets/TextField.hxx
  src/engine/ui/widgets/Tooltip.hxx
Labels: user interface

#242 Unittests
  .travis.yml
  src/engine/WindowManager.cxx
  src/engine/ui/widgets/Text.cxx
  tests/CMakeLists.txt
  tests/engine/Engine.cxx
  tests/engine/ResourcesManager.cxx
  tests/engine/WindowManager.cxx
  tests/ui/widgets/Text.cxx
Labels: unittest

#252 Slider UIElement
  .gitignore
  src/engine/EventManager.cxx
  src/engine/ui/widgets/Slider.cxx
  src/engine/ui/widgets/Slider.hxx
Labels: user interface
