Repository CytopiaTeam/Cytopia, pull requests merged in 2022-04, with the labels that each got.

#848 Fix overplacement issues
  src/engine/GameObjects/MapNode.cxx
  src/engine/Map.cxx
Labels: bug, core

#859 Vsync
  data/resources/data/UILayout.json
  data/resources/settings.json
  src/engine/UIManager.cxx
  src/engine/WindowManager.cxx
  src/engine/ui/widgets/Checkbox.cxx
  src/engine/ui/widgets/Checkbox.hxx
Labels: user interface, core

#860 Fix z order
  src/engine/GameObjects/MapNode.hxx
  src/engine/Map.cxx
  src/engine/map/TerrainGenerator.cxx
Labels: bug, core

#851 refactor MapNode::isPlacementAllowed
  src/engine/GameObjects/MapNode.cxx
  src/engine/TileManager.hxx
Labels: refactoring

#863 Update tile types
  data/resources/data/TileData.json
  src/engine/TileManager.cxx
  src/engine/basics/tileData.hxx
  src/game/ZoneManager.cxx
Labels: refactoring, core

#867 README.md: Adding all dependencies
  README.md
Labels: documentation

#873 Add a setting option to write the error log to a file
  data/resources/settings.json
  src/engine/basics/Settings.cxx
  src/engine/basics/Settings.hxx
  src/engine/common/JsonSerialization.hxx
  src/util/Exception.hxx
  src/util/LOG.cxx
  src/util/LOG.hxx
  tests/CMakeLists.txt
Labels: crash

#856 Refactor set tile
  src/engine/Engine.hxx
  src/engine/EventManager.cxx
  src/engine/GameObjects/MapNode.cxx
  src/engine/GameObjects/MapNode.hxx
  src/engine/Map.cxx
  src/engine/Map.hxx
  src/engine/TileManager.cxx
  src/engine/TileManager.hxx
  src/engine/UIManager.cxx
  src/game/ZoneArea.cxx
Labels: refactoring, core

#875 Minor refactor for codebase to prefer constructor initializer lists
  src/engine/GameObjects/MapNode.cxx
Labels: refactoring

#868 Add options to build with ASan/UBSan/TSan
  .github/workflows/build-game.yml
  CMakeLists.txt
  src/CMakeLists.txt
Labels: build

#882 More doxy fixes
  src/engine/Engine.hxx
  src/engine/EventManager.hxx
  src/engine/GameObjects/MapNode.hxx
  src/engine/Map.hxx
  src/engine/ResourcesManager.hxx
  src/engine/TileManager.hxx
  src/engine/UIManager.hxx
  src/engine/WindowManager.hxx
  src/engine/audio/Soundtrack.hxx
  src/engine/basics/Camera.hxx
  src/engine/basics/GameStates.hxx
  src/engine/basics/PointFunctions.hxx
  src/engine/basics/Settings.hxx
  src/engine/basics/isoMath.hxx
  src/engine/basics/point.hxx
  src/engine/basics/tileData.hxx
  src/engine/basics/utils.hxx
  src/engine/common/enums.hxx
  src/engine/map/MapLayers.hxx
  src/engine/map/TerrainGenerator.hxx
  src/engine/ui/basics/ButtonGroup.hxx
  src/engine/ui/basics/Layout.hxx
  src/engine/ui/basics/UIElement.hxx
  src/engine/ui/menuGroups/IMenuGroup.hxx
  src/engine/ui/widgets/Button.hxx
  src/engine/ui/widgets/Slider.hxx
  src/engine/ui/widgets/Text.hxx
  src/engine/ui/widgets/Tooltip.hxx
  src/game/ZoneArea.hxx
  src/game/ZoneManager.hxx
  src/services/AudioMixer.hxx
  src/services/GameClock.hxx
  src/util/Filesystem.hxx
  src/util/LOG.hxx
  src/util/PriorityQueue.hxx
Labels: documentation

#864 Map refactoring
  src/engine/Map.cxx
  src/engine/Map.hxx
  src/engine/basics/PointFunctions.cxx
  src/engine/basics/PointFunctions.hxx
  src/engine/basics/point.hxx
Labels: refactoring, core

#885 Refactored DropdownMenu into ComboBox
  src/CMakeLists.txt
  src/engine/UIManager.hxx
  src/engine/ui/widgets/Combobox.cxx
  src/engine/ui/widgets/Combobox.hxx
  src/engine/ui/widgets/TextField.cxx
  src/engine/ui/widgets/TextField.hxx
Labels: refactoring, user interface
