Repository CytopiaTeam/Cytopia, pull requests merged in 2022-06, with the labels that each got.

#980 Added imgui to list of dependencies in README
  README.md
Labels: documentation

#979 imgui: moved ingame pause menu to imgui logic
  data/resources/data/UILayout.json
  external/imgui/imgui.cpp
  external/imgui/imgui.h
  src/CMakeLists.txt
  src/Game.cxx
  src/Game.hxx
  src/engine/EventManager.cxx
  src/engine/EventManager.hxx
  src/engine/UIManager.cxx
  src/engine/UIManager.hxx
  src/game/ui/PauseMenu.cxx
  src/game/ui/PauseMenu.hxx
  src/game/ui/SettingsMenu.cxx
  src/game/ui/SettingsMenu.hxx
Labels: user interface

#985 Converted inline comments to doxygen syntax
  src/engine/map/TerrainGenerator.hxx
Labels: documentation

#982 New UI cleaning and docs
  src/Game.cxx
  src/Game.hxx
  src/MainMenu.cxx
  src/MainMenu.hxx
  src/engine/UIManager.hxx
  src/engine/WindowManager.hxx
Labels: documentation

#986 Removed unused widgets after ImGui refactor
  src/CMakeLists.txt
  src/engine/UIManager.cxx
  src/engine/UIManager.hxx
  src/engine/ui/widgets/Checkbox.cxx
  src/engine/ui/widgets/Checkbox.hxx
  src/engine/ui/widgets/Combobox.cxx
  src/engine/ui/widgets/Combobox.hxx
  src/engine/ui/widgets/Slider.cxx
  src/engine/ui/widgets/Slider.hxx
  tests/CMakeLists.txt
  tests/ui/widgets/Checkbox.cxx
  tests/ui/widgets/Combobox.cxx
  tests/ui/widgets/Slider.cxx
Labels: refactoring, user interface
