Repository CytopiaTeam/Cytopia, pull requests merged in 2022-05, with the labels that each got.

#888 Add more Layers
  src/engine/GameObjects/MapNode.cxx
  src/engine/GameObjects/MapNode.hxx
  src/engine/Map.cxx
  src/engine/Sprite.cxx
  src/engine/Sprite.hxx
  src/engine/TileManager.cxx
  src/engine/common/enums.hxx
  src/engine/map/MapLayers.cxx
Labels: bug

#887 Created unit tests for UI widgets
  src/engine/ui/widgets/Combobox.cxx
  tests/CMakeLists.txt
  tests/ui/widgets/Button.cxx
  tests/ui/widgets/Checkbox.cxx
  tests/ui/widgets/Combobox.cxx
  tests/ui/widgets/Slider.cxx
  tests/ui/widgets/Text.cxx
  tests/ui/widgets/Tooltip.cxx
Labels: user interface, unittest

#889 Fix new game and load game buttons
  data/resources/settings.json
  src/engine/Engine.cxx
  src/engine/GameObjects/MapNode.hxx
  src/engine/common/JsonSerialization.hxx
Labels: bug

#854 Power Manager implementation
  data/resources/data/TileData.json
  src/CMakeLists.txt
  src/engine/GameObjects/MapNode.hxx
  src/engine/Map.cxx
  src/engine/Map.hxx
  src/game/GamePlay.hxx
  src/game/PowerGrid.cxx
  src/game/PowerGrid.hxx
  src/game/PowerManager.cxx
  src/game/PowerManager.hxx
Labels: enhancement, core

#891 Added extra powerline frames
  data/resources/data/TileData.json
  data/resources/images/buildings/power plants/pow_1x1_RuralPowerlines.png
  src/engine/GameObjects/MapNode.cxx
  src/engine/TileManager.hxx
Labels: graphics

#901 Signals Mediator
  src/CMakeLists.txt
  src/engine/Map.cxx
  src/engine/Map.hxx
  src/engine/ui/basics/UIElement.hxx
  src/game/PowerManager.cxx
  src/game/ZoneManager.cxx
  src/game/ZoneManager.hxx
  src/util/Signal.hxx
  src/util/SignalMediator.hxx
Labels: core

#902 Minor UI refactoring
  src/CMakeLists.txt
  src/engine/UIManager.cxx
  src/engine/ui/basics/UIElement.hxx
  src/engine/ui/widgets/Bar.cxx
  src/engine/ui/widgets/Bar.hxx
  src/engine/ui/widgets/Button.cxx
  src/engine/ui/widgets/Button.hxx
  src/engine/ui/widgets/Checkbox.cxx
  tests/ui/widgets/Checkbox.cxx
Labels: refactoring, user interface

#909 More minor refactoring/changes for UI widgets
  src/engine/UIManager.cxx
  src/engine/ui/basics/UIElement.cxx
  src/engine/ui/basics/UIElement.hxx
  src/engine/ui/widgets/Button.hxx
  src/engine/ui/widgets/Checkbox.cxx
  src/engine/ui/widgets/Checkbox.hxx
  src/engine/ui/widgets/Slider.cxx
  src/engine/ui/widgets/Slider.hxx
Labels: refactoring, user interface

#913 Implement middle click eyedropper tool feature
  src/engine/EventManager.cxx
  src/engine/EventManager.hxx
  src/engine/GameObjects/MapNode.cxx
  src/engine/Map.cxx
  src/engine/Map.hxx
  src/engine/common/enums.hxx
Labels: enhancement

#923 Code smell fixes
  src/Game.cxx
  src/engine/EventManager.cxx
  src/engine/GameObjects/MapNode.cxx
  src/engine/GameObjects/MapNode.hxx
  src/engine/Map.cxx
  src/engine/TileManager.cxx
  src/engine/audio/Soundtrack.cxx
  src/engine/basics/PointFunctions.cxx
  src/engine/basics/Settings.hxx
  src/engine/basics/utils.cxx
  src/engine/map/MapLayers.cxx
  src/engine/ui/widgets/Combobox.cxx
  src/game/ZoneArea.cxx
  src/services/AudioMixer.cxx
  src/services/ResourceManager.cxx
  src/util/Exception.cxx
Labels: refactoring

#949 new fonts
  data/resources/fonts/Licenses/PressStart2P.txt
  data/resources/fonts/Licenses/advanced_pixel-7.txt
  data/resources/fonts/Licenses/alphabeta.txt
  data/resources/fonts/Licenses/editundo.txt
  data/resources/fonts/Licenses/license.txt
  data/resources/fonts/Licenses/lilliput steps.pdf
  data/resources/fonts/Licenses/mini_pixel-7.txt
  data/resources/fonts/Licenses/pixelFJ8pt1.txt
  data/resources/fonts/Licenses/sources.txt
  data/resources/fonts/PressStart2P.ttf
  data/resources/fonts/advanced_pixel-7.ttf
  data/resources/fonts/alphbeta.ttf
  data/resources/fonts/editundo.ttf
  data/resources/fonts/edundot.ttf
  data/resources/fonts/edunline.ttf
  data/resources/fonts/lilliput steps.ttf
  data/resources/fonts/mini_pixel-7.ttf
  data/resources/fonts/pixelFJ8pt1.TTF
  data/resources/settings.json
Labels: core

#936 ui: config: read fontsize from settings.json
  data/resources/data/UILayout.json
  data/resources/settings.json
  src/engine/UIManager.cxx
  src/engine/basics/Settings.hxx
  src/engine/common/JsonSerialization.hxx
  src/engine/ui/basics/Layout.hxx
  src/engine/ui/widgets/Button.cxx
  src/engine/ui/widgets/Button.hxx
  src/engine/ui/widgets/Text.cxx
Labels: user interface

#966 Fix zones after load
  src/Game.cxx
  src/Game.hxx
  src/MainMenu.cxx
  src/engine/UIManager.cxx
  src/engine/common/platform.hxx
  src/engine/map/MapFunctions.cxx
  src/engine/map/MapFunctions.hxx
  src/engine/ui/basics/Layout.hxx
  src/engine/ui/widgets/Button.cxx
  src/engine/ui/widgets/Text.cxx
  src/game/GamePlay.cxx
  src/game/PowerManager.cxx
  src/game/PowerManager.hxx
  src/game/ZoneManager.cxx
  src/game/ZoneManager.hxx
  src/util/OSystem.cxx
  src/util/OSystem.hxx
  tests/engine/MapFunctions.cxx
  tests/game/PowerManager.cxx
Labels: gameplay
