Repository CytopiaTeam/Cytopia, pull requests merged in 2022-03, with the labels that each got.

#805 Gameplay class
  src/CMakeLists.txt
  src/Game.cxx
  src/Game.hxx
  src/engine/WindowManager.cxx
  src/engine/WindowManager.hxx
  src/game/GamePlay.cxx
  src/game/GamePlay.hxx
Labels: refactoring

#808 Fixed doxygen syntax
  src/engine/GameObjects/MapNode.hxx
  src/engine/Map.hxx
  src/engine/UIManager.hxx
  src/engine/audio/Soundtrack.hxx
  src/engine/basics/Settings.hxx
  src/engine/basics/signal.hxx
  src/engine/ui/basics/ButtonGroup.hxx
  src/engine/ui/widgets/Text.hxx
  src/services/GameClock.hxx
  src/util/Exception.hxx
  src/util/filesystem.hxx
Labels: documentation

#811 Fixed doxy syntax to fix documentation for variables.
  src/engine/basics/tileData.hxx
Labels: documentation

#814 Mass doxy fixes
  src/engine/EventManager.hxx
  src/engine/UIManager.hxx
  src/engine/WindowManager.hxx
  src/engine/basics/GameStates.hxx
  src/engine/basics/point.hxx
  src/engine/basics/signal.hxx
  src/engine/basics/tileData.hxx
  src/engine/ui/basics/Layout.hxx
  src/engine/ui/basics/UIElement.hxx
Labels: documentation

#823 add dezone button to construction menu
  data/resources/data/UIData.json
  data/resources/data/UILayout.json
  data/resources/images/ui/buttons/dezone.png
  src/engine/UIManager.cxx
Labels: user interface, core

#842 Added Rural Powerlines
  data/resources/data/TileData.json
  data/resources/images/buildings/power plants/pow_1x1_RuralPowerlines.png
Labels: graphics
