Repository CytopiaTeam/Cytopia, pull requests merged in 2022-07, with the labels that each got.

#988 imgui: move build menu to imgui logic
  data/resources/data/UILayout.json
  external/imgui/imgui.cpp
  external/imgui/imgui.h
  external/imgui/imgui_internal.h
  external/imgui/imgui_widgets.cpp
  src/CMakeLists.txt
  src/Game.cxx
  src/MainMenu.cxx
  src/engine/EventManager.cxx
  src/engine/UIManager.cxx
  src/engine/UIManager.hxx
  src/engine/basics/tileData.hxx
  src/engine/map/MapFunctions.hxx
  src/engine/ui/basics/Layout.cxx
  src/game/ui/BuildMenu.cxx
  src/game/ui/BuildMenu.hxx
  src/game/ui/PauseMenu.cxx
  src/game/ui/SettingsMenu.cxx
  src/main.cxx
  tests/CMakeLists.txt
  tests/engine/UIManager.cxx
Labels: user interface

#999 Add metainfo files, and svg icon
  data/resources/images/app_icons/cytopia_icon.svg
  data/setup/net.cytopia.Cytopia.metainfo.xml
Labels: build

#991 ui: add time controls area
  external/imgui/imgui_widgets.cpp
  src/CMakeLists.txt
  src/Game.cxx
  src/game/ui/GameTimeMenu.cxx
  src/game/ui/GameTimeMenu.hxx
  src/services/GameClock.cxx
  src/services/GameClock.hxx
Labels: user interface

#1005 ui: remove native widgets from repo
  src/CMakeLists.txt
  src/Game.cxx
  src/MainMenu.cxx
  src/engine/EventManager.cxx
  src/engine/EventManager.hxx
  src/engine/Layout.hxx
  src/engine/UIManager.cxx
  src/engine/UIManager.hxx
  src/engine/basics/GameStates.hxx
  src/engine/ui/basics/Layout.cxx
  src/engine/ui/basics/Layout.hxx
  src/engine/ui/basics/UIElement.cxx
  src/engine/ui/basics/UIElement.hxx
  src/engine/ui/widgets/Text.cxx
  src/engine/ui/widgets/Text.hxx
  src/game/ui/BuildMenu.cxx
  src/game/ui/BuildMenu.hxx
  src/game/ui/GameTimeMenu.cxx
  src/game/ui/LoadMenu.cxx
  src/game/ui/PauseMenu.cxx
  src/game/ui/SettingsMenu.cxx
  tests/CMakeLists.txt
  tests/engine/UIManager.cxx
  tests/ui/widgets/Text.cxx
Labels: refactoring

#871 Remove install dir override
  CMakeLists.txt
Labels: Stale

#1006 AudioMixer refactor
  src/services/AudioMixer.cxx
  src/services/AudioMixer.hxx
Labels: refactoring, audio
